FROM debian:bullseye

# Variables d'env
ENV DEBIAN_FRONTEND=noninteractive

# Installation de mariadb
RUN apt-get update && \
    apt-get install -y mariadb-server && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copie des fichiers
COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/script.sh /script.sh
RUN chmod +x /script.sh

# Port
EXPOSE 3306

# Commande au démarrage
CMD ["/script.sh"]
